# disable the newline at the start of the prompt
add_newline = false

format = """\
  $time\
  $directory\
  $git_branch\
  $git_status\
  $nodejs\
  $golang\
  $python\
  $ruby\
  $rust\
  $line_break\
  $character\
"""

# replace the prompt character
[character]
success_symbol = "[❯](bold purple)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold purple)"

# only show current directory name
# remove directory, and make it blue
[directory]
truncation_length = 1
style = "blue"
format = "[$path ]($style)[$read_only]($read_only_style)"

# do not put prompt character on new line
# might revisit this in the future...
[line_break]
# disabled = true

# show the time in the prompt
[time]
disabled = false
style = "bright-black"
time_format = "[%T] "
format = "[$time]($style)"

[git_branch]
style = "purple"

[git_status]
style = "yellow"

# remove bold styling from language prompts
[golang]
style = "cyan"

[nodejs]
style = "green"
symbol = "⬢ "

[python]
style = "yellow"

[ruby]
style = "red"

[rust]
style = "red"
symbol = "⚙ "
