# disable the newline at the start of the prompt
add_newline = false

prompt_order = [
  "time",
  "directory",
  "git_branch",
  "git_status",
  "nodejs",
  "golang",
  "python",
  "ruby",
  "rust",
  "line_break",
  "character"
]

# replace the prompt character
[character]
# symbol = "»"
style_success = "purple"
style_failure = "red"

# only show current directory name
# remove directory prefix, and make it blue
[directory]
truncation_length = 1
style = "blue"
prefix = ""

# do not put prompt character on new line
# might revisit this in the future...
[line_break]
# disabled = true

# show the time in the prompt
[time]
disabled = false
style = "bright-black"
format = "[%T]"

[git_branch]
style = "purple"

[git_status]
style = "yellow"

# remove bold styling from language prompts
[golang]
style = "cyan"

[nodejs]
style = "green"

[python]
style = "yellow"

[ruby]
style = "red"

[rust]
style = "red"
symbol = "⚙ "
