# disable the newline at the start of the prompt
add_newline = false

# $time\ was originally at the beginning, but dropping it for extra space
# add/remove $line_break\ before $character\ to get prompt character on same line as prompt

format = """\
  $directory\
  $git_branch\
  $git_status\
  $golang\
  $line_break\
  $time\
  $character\
"""

[fill]
symbol = ' '

# replace the prompt character
[character]
success_symbol = "[❯](bold purple)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold purple)"

# only show current and parent directory
[directory]
truncation_length = 2
style = "bright-blue"
format = "[$path ]($style)[$read_only]($read_only_style)"

[line_break]
# disabled = true

# show the time in the prompt
[time]
disabled = false
style = "bright-black" # use with all other themes
# style = "#506686" # use with electron-highlighter theme
time_format = "[%T]"
format = "[$time]($style) "

[git_branch]
style = "purple"
# symbol = "git"
symbol = ""
format = '[$symbol $branch]($style) '

[git_status]
style = "yellow"
deleted = "×"

# remove bold styling from language prompts
[golang]
style = "cyan"
symbol = " "
format = '[$symbol$version]($style) '

[nodejs]
style = "bright-green"
symbol = " "
format = '[$symbol$version]($style) '

[kubernetes]
disabled = false
format = '[$symbol$context]($style)'
